on:
  push:
    tags: ['*']

name: release

jobs:
  release:
    name: release
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        os: [linux]
        arch:
          - amd64
          - arm
          - arm64
        include:
          - os: linux
            arch: amd64
            packages: gcc
            cc: gcc
          - os: linux
            arch: arm
            packages: gcc-arm-linux-gnueabihf
            cc: arm-linux-gnueabihf-gcc
          - os: linux
            arch: arm64
            packages: gcc-aarch64-linux-gnu
            cc: aarch64-linux-gnu-gcc
    env:
      GOOS: '${{ matrix.os }}'
      GOARCH: '${{ matrix.arch }}'
      CC: '${{ matrix.cc }}'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17'
      - run: sudo apt-get install -y ${{ matrix.packages }}
      - run: make build RELEASE=1
      - run: |
          name=linux_dvb_exporter-v$(cat VERSION).$GOOS-$GOARCH
          mkdir "$name"
          mv README.md "${name}/"
          mv LICENSE "${name}/"
          mv linux_dvb_exporter "${name}/"
          tar cf "$name.tar.gz" "$name"
      - uses: softprops/action-gh-release@v1
        with:
          files: linux_dvb_exporter-*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
